config/routes.rb
Rails.application.routes.draw do
  resources :statuses, only: [:create, :show] do
    post 'bulk_create', on: :collection
  end
  devise_for :admins
  resources :devices, only: [:index, :create, :show]
  resources :admins, except: [:new, :create]
  resources :notifications, only: [:index, :destroy]
  root to: 'devices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :statuses

  before_create :add_token

  validates :serial_number, :firmware_version, presence: true

  def add_token
    self.token = SecureRandom.hex(10)
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_admin!, except: :create
  skip_before_action :verify_authenticity_token, only: :create

  before_action :set_device, only: :show

  # GET /devices
  # GET /devices.json
  def index
    serial_number = params[:serial_number]
    if serial_number.present?
      @devices = Device.where('serial_number LIKE ?', "%#{serial_number}%")
    else
      @devices = Device.all
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    time_range = params[:time_range]
    today = Date.today
    case(time_range)
      when 'YEAR'
        @min_date = today.beginning_of_year
        @max_date = today.end_of_year
      when 'MONTH'
        @min_date = today.beginning_of_month
        @max_date = today.end_of_month
      when 'WEEK'
        @min_date = today.beginning_of_week
        @max_date = today.end_of_week
      else
        @min_date = today.beginning_of_day
        @max_date = today.end_of_day
    end
    @statuses = @device.statuses.where(collected_at: @min_date..@max_date)
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:serial_number, :firmware_version, :token)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/index.html.erb
<h1>Devices</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Serial number</th>
      <th>Registration Date</th>
      <th>Firmware version</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.serial_number, device %></td>
        <td><%= device.created_at.to_date %></td>
        <td><%= device.firmware_version %></td>
        <td><%= link_to 'Statuses', device %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @device.serial_number %></h1>

<p>
  <strong>Registration Date:</strong>
  <%= @device.created_at.to_date %>
</p>

<p>
  <strong>Firmware version:</strong>
  <%= @device.firmware_version %>
</p>
Display Current: <%= link_to 'Day', device_path(@device, time_range: 'DAY') %> |
<%= link_to 'Week', device_path(@device, time_range: 'WEEK') %> |
<%= link_to 'Month', device_path(@device, time_range: 'MONTH') %> |
<%= link_to 'Year', device_path(@device, time_range: 'YEAR') %>
<% if @statuses.present? %>
  <h2>Sensor Graphs</h2>
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <h3>Temperature</h3>
          <%= line_chart @statuses.pluck(:collected_at, :temperature), xmin: @min_date, xmax: @max_date, xtitle: 'Time', ytitle: 'Temperature (in Celcius)' %>
        </div>
        <div class="col-sm-6">
          <h3>Air Humidity</h3>
          <%= line_chart @statuses.pluck(:collected_at, :air_humidity), xmin: @min_date, xmax: @max_date, xtitle: 'Time', ytitle: 'Air Humidity Percentage' %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <h3>Carbon Monoxide</h3>
          <%= line_chart @statuses.pluck(:collected_at, :carbon_monoxide), xmin: @min_date, xmax: @max_date, xtitle: 'Time', ytitle: 'Carbon Monoxide Level' %>

        </div>
      </div>
    </div>
  <h2>Raw Data</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Temperature</th>
          <th>Air humidity</th>
          <th>Carbon monoxide</th>
          <th>Health status</th>
          <th>Collected at</th>
        </tr>
      </thead>

      <tbody>
      <% @statuses.each do |status| %>
        <tr>
          <td><%= status.temperature %></td>
          <td><%= status.air_humidity %></td>
          <td><%= status.carbon_monoxide %></td>
          <td><%= status.health_status %></td>
          <td><%= status.collected_at %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
    <div class="alert alert-warning" role="alert">
      This device has not reported any statuses for the selected time range.
    </div>
<% end %>
<%= link_to 'Back', devices_path %>