config/routes.rb
Rails.application.routes.draw do
  resources :statuses, only: [:create, :show] do
    post 'bulk_create', on: :collection
  end
  devise_for :admins
  resources :devices, only: [:index, :create, :show]
  resources :admins, except: [:new, :create]
  resources :notifications, only: [:index, :destroy]
  root to: 'devices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  enum level: [:warning, :danger]

  belongs_to :status
  has_one :device, through: :status

  scope :active, -> { where(dismissed: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_notification, only: [:show, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.active
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    respond_to do |format|
      if @notification.update(dismissed: true)
        format.html { redirect_to notifications_url, notice: 'Notification was successfully dismissed.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:level, :status, :dismissed)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<p id="notice"></p>

<h1>Notifications</h1>

<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Device</th>
      <th>Message</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr class="table-<%= notification.level %>">
        <td><%= notification.status.collected_at %></td>
        <td><%= link_to notification.device.serial_number, notification.device %></td>
        <td><%= notification.message %></td>
        <td><%= link_to 'Dismiss', notification, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level:</strong>
  <%= @notification.level %>
</p>

<p>
  <strong>Status:</strong>
  <%= @notification.status %>
</p>

<p>
  <strong>Dismissed:</strong>
  <%= @notification.dismissed %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>