config/routes.rb
Rails.application.routes.draw do
  resources :statuses, only: [:create, :show] do
    post 'bulk_create', on: :collection
  end
  devise_for :admins
  resources :devices, only: [:index, :create, :show]
  resources :admins, except: [:new, :create]
  resources :notifications, only: [:index, :destroy]
  root to: 'devices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Theorem AC</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Devices', devices_path, { class: 'nav-link'} %>
      </li>
      <li class="nav-item">
        <%= link_to 'Notifications', notifications_path, { class: 'nav-link'} %>
      </li>
      <li class="nav-item">
        <%= link_to 'Admins', admins_path, { class: 'nav-link' } %>
      </li>
      <li class="nav-item">
        <%= link_to 'Invite Admin', new_admin_invitation_path, { class: 'nav-link'} %>
      </li>
      <li class="nav-item">
        <%= link_to('Logout', destroy_admin_session_path, method: :delete, class: 'nav-link') %>
      </li>
    </ul>
    <%= form_tag(devices_path, method: :get, class: 'form-inline my-2 my-lg-0') do %>
        <%= text_field_tag :serial_number, nil, class: 'form-control mr-sm-2', placeholder: 'Serial Number' %>
        <%= submit_tag 'Search', class:'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheoremAc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if admin_signed_in? %>
    <%= render partial: 'layouts/navbar' %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <% if notice.present? %>
            <% if notice.include?('successfully') %>
                <div class="alert alert-success"><%= notice %></div>
            <% else %>
                <div class="alert alert-dark"><%= notice %></div>
            <% end %>
        <% end %>
        <% if admin_signed_in? %>
          <% unless @danger_count.zero? %>
              <div class="alert alert-danger">There are currently <%= link_to "#{@danger_count} devices", notifications_path %> with safety concerns!!</div>
          <% end %>
          <% unless @warning_count.zero? %>
            <div class="alert alert-warning">There are currently <%= link_to "#{@warning_count} devices", notifications_path %> devices in need of service or filters</div>
          <% end %>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>